"""
FastAPI backend for CandidateIQ.

Serves pre-ranked results from data/top100.json (generated by run.py).
The ranking itself happens offline via run.py — the API just serves the results.

Start with:
    uvicorn backend.main:app --reload --port 8000
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
import os

app = FastAPI(title="CandidateIQ — Redrob AI Recruitment Platform")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Load pre-ranked top100 on startup ─────────────────────────────────────────

CANDIDATES_DB: list[dict] = []

def _load():
    global CANDIDATES_DB
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(base, "data", "top100.json")
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            CANDIDATES_DB = json.load(f)
        print(f"Loaded {len(CANDIDATES_DB)} ranked candidates from {path}")
    else:
        print(f"WARNING: {path} not found. Run `python run.py` first.")

_load()

# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "message": "CandidateIQ API — Redrob Hackathon",
        "candidates_loaded": len(CANDIDATES_DB),
        "endpoints": ["/api/top100", "/api/candidates/{candidate_id}", "/api/stats"],
    }


@app.get("/api/top100")
def get_top100():
    """Returns the full ranked top-100 list. Called by the React frontend."""
    if not CANDIDATES_DB:
        raise HTTPException(
            status_code=503,
            detail="No candidates loaded. Run `python run.py` to generate top100.json first.",
        )
    return CANDIDATES_DB


@app.get("/api/candidates/{candidate_id}")
def get_candidate(candidate_id: str):
    """Returns a single candidate by ID."""
    for c in CANDIDATES_DB:
        if c.get("candidate_id") == candidate_id:
            return c
    raise HTTPException(status_code=404, detail=f"Candidate {candidate_id} not found")


@app.get("/api/stats")
def get_stats():
    """Dashboard stats for the UI header."""
    if not CANDIDATES_DB:
        return {}
    scores = [c["score"] for c in CANDIDATES_DB]
    return {
        "total": len(CANDIDATES_DB),
        "avg_score": round(sum(scores) / len(scores), 3),
        "strong_hire": sum(1 for c in CANDIDATES_DB if c.get("decision") == "Strong Hire"),
        "immediate":   sum(1 for c in CANDIDATES_DB if c.get("interview_priority") == "Immediate"),
        "high_risk":   sum(1 for c in CANDIDATES_DB if c.get("risk") == "High"),
        "avg_confidence": round(
            sum(c.get("confidence", 0) for c in CANDIDATES_DB) / len(CANDIDATES_DB), 1
        ),
    }
